import Link from "next/link";
import { notFound } from "next/navigation";
import { getChange, getActionsForChange, siteName, siteCC } from "../../../../lib/data/store";
import { ChangeDetectionService } from "../../../../lib/services/change-detection.service";
import { mockRegulatoryFeed } from "../../../../lib/integrations/regulatory-feed/mock";
import { mockAiProvider } from "../../../../lib/integrations/ai/mock";
import { getCurrentUser } from "../../../../lib/auth/current-user";
import { can } from "../../../../lib/auth/rbac";
import { DiffView } from "../../../../components/diff-view";
import { ChangeActions } from "../../../../components/change-actions";
import { Crumbs, PageHead, SevPill, StatusPill, ActionPill, flag, fmt, jurCC } from "../../../../components/ui";

export default async function ChangeDetail({ params }: { params: Promise<{ changeId: string }> }) {
  const { changeId } = await params;
  const change = await getChange(changeId);
  if (!change) notFound();

  const user = await getCurrentUser();
  const canApprove = can(user, "approve_assessment");
  const actions = await getActionsForChange(changeId);

  // Run the REAL diff engine + change-detection service when source versions exist.
  let detection: Awaited<ReturnType<ChangeDetectionService["analyze"]>> | null = null;
  if (change.prevVersion && change.currVersion) {
    const versions = await mockRegulatoryFeed.getVersions(change.regId);
    if (versions.find((v) => v.versionLabel === change.prevVersion) && versions.find((v) => v.versionLabel === change.currVersion)) {
      const detector = new ChangeDetectionService(mockRegulatoryFeed, mockAiProvider);
      detection = await detector.analyze(change.regId, change.prevVersion, change.currVersion);
    }
  }

  return (
    <>
      <Crumbs items={["Change Control", change.id]} />
      <PageHead title="Regulatory Change Control"
        subtitle="Version-controlled comparison · every change is traceable, every impact has an owner, every decision is auditable." />

      <div className="card" style={{ marginBottom: 16, borderLeft: `4px solid ${change.sev === "CRITICAL" ? "var(--red)" : change.sev === "HIGH" ? "var(--amber)" : "var(--blue)"}` }}>
        <div className="cb" style={{ display: "flex", gap: 18, alignItems: "center", flexWrap: "wrap" }}>
          <div style={{ flex: 1, minWidth: 280 }}>
            <div style={{ fontSize: 11, fontWeight: 700, letterSpacing: ".5px", color: "var(--muted)" }}>{change.id} · <Link href={`/baseline/${change.regId}`} style={{ color: "var(--blue)" }}>{change.regId}</Link></div>
            <div style={{ fontSize: 17, fontWeight: 700, margin: "3px 0" }}>{change.title}</div>
            <div style={{ display: "flex", gap: 8, flexWrap: "wrap", marginTop: 6 }}>
              <SevPill s={change.sev} /><span className="tag">{change.cat}</span><StatusPill s={change.status} />
            </div>
          </div>
          <div style={{ textAlign: "right" }}>
            <div className="muted sm">Effective</div><div style={{ fontSize: 18, fontWeight: 800 }}>{fmt(change.eff)}</div>
            <div className="sm muted">Owner: {change.owner}</div>
          </div>
        </div>
      </div>

      {detection ? (
        <>
          <div className="section-title">Side-by-side comparison — {change.regId} · generated by the diff engine</div>
          <DiffView diffs={detection.comparison.clauseDiffs}
            prevVersion={`${change.prevVersion} · ${detection.comparison.stats.amended + detection.comparison.stats.deleted} prior clauses`}
            currVersion={`${change.currVersion} · effective ${fmt(change.eff)}`} />

          <div className="grid" style={{ gridTemplateColumns: "1.5fr 1fr" }}>
            <div>
              <div className="aibox" style={{ marginBottom: 16 }}>
                <div className="aih">✦ AI-assisted impact analysis
                  <span className="pill p-amber"><span className="pd" />{detection.assessmentLifecycle} · Requires expert review</span>
                  <span className="conf" style={{ marginLeft: "auto" }}>Confidence: {detection.aiDraft.confidence}</span>
                </div>
                <p style={{ margin: "0 0 8px", fontSize: 13, lineHeight: 1.65 }}>{detection.aiDraft.summary}</p>
                <p style={{ margin: 0, fontSize: 13, lineHeight: 1.65 }}><b>Likely business impact:</b> {detection.aiDraft.businessImpact}</p>
                <div style={{ fontSize: 11, color: "var(--muted)", marginTop: 8, borderTop: "1px solid #e0d8f5", paddingTop: 8 }}>
                  Generated by AI Service ({detection.aiDraft.aiModel}) · grouped from the deterministic text-diff · raw diff stored separately · not a final compliance decision.
                </div>
              </div>
              <div className="card"><div className="ch"><h3>Materiality &amp; applicability (deterministic)</h3></div>
                <div className="cb"><div className="kv" style={{ gridTemplateColumns: "180px 1fr" }}>
                  <div className="k">Diff stats</div><div>{detection.comparison.stats.added} added · {detection.comparison.stats.amended} amended · {detection.comparison.stats.deleted} removed</div>
                  <div className="k">Material signals</div><div>{detection.comparison.signals.map((s, i) => <span className="tag" key={i} style={{ marginRight: 4 }}>{s.clauseNo} {s.kind.replace("_", " ").toLowerCase()} ({s.direction})</span>)}</div>
                  <div className="k">Derived severity</div><div><SevPill s={detection.severity} /></div>
                  <div className="k">Compliance impact</div><div><span className="pill p-red"><span className="pd" />{detection.complianceImpact.replace(/_/g, " ").toLowerCase()}</span></div>
                  <div className="k">Categories</div><div>{detection.categories.map((c) => <span className="tag" key={c} style={{ marginRight: 4 }}>{c}</span>)}</div>
                  <div className="k">Affected sites</div><div>{change.sites.map((s) => <span className="tag" key={s} style={{ marginRight: 4 }}>{flag(siteCC(s))} {siteName(s)}</span>)}</div>
                </div></div>
              </div>
            </div>
            <div>
              <div className="card" style={{ marginBottom: 16 }}><div className="ch"><h3>Decision &amp; workflow</h3></div>
                <div className="cb"><ChangeActions changeId={change.id} canApprove={canApprove} /></div>
              </div>
              <div className="card"><div className="ch"><h3>Required actions</h3></div>
                <div className="cb">{actions.length ? actions.map((a) => (
                  <div key={a.id} style={{ display: "flex", justifyContent: "space-between", alignItems: "center", padding: "7px 0", borderBottom: "1px solid var(--line2)" }}>
                    <div><div style={{ fontWeight: 600, fontSize: 12.5 }}>{a.title}</div><div className="sm muted">{a.owner} · due {fmt(a.due)}</div></div>
                    <ActionPill s={a.status} />
                  </div>
                )) : <div className="muted sm">No actions yet — create an action plan.</div>}</div>
              </div>
            </div>
          </div>
        </>
      ) : (
        <div className="card"><div className="cb">
          <p className="muted">The full clause-level comparison renders once both source versions for <b>{change.regId}</b> are ingested by the regulatory-feed adapter. The deterministic diff engine then produces the side-by-side view, material signals and severity automatically.</p>
          <p>Try <Link href="/change/CHG-2038" style={{ color: "var(--blue)", fontWeight: 600 }}>CHG-2038 (TA Luft)</Link> to see the engine output end-to-end.</p>
        </div></div>
      )}
    </>
  );
}
